interface ZIF_I_19_RENTALTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_19_RENTALTP,
 CREATE_ZI_19_RENTALTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C11B5FD',
 DELETE_ZI_19_RENTALTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C1235FD',
 LOCK_ZI_19_RENTALTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C10F5FD',
 SAVE_ZI_19_RENTALTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C12B5FD',
 UNLOCK_ZI_19_RENTALTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C1135FD',
 UPDATE_ZI_19_RENTALTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C11F5FD',
 VALIDATE_ZI_19_RENTALTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EEDA681131E0C1275FD',
      END OF ZI_19_RENTALTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_19_RENTALTP,
        BEGIN OF LOCK_ZI_19_RENTALTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_19_RENTALTP,
        BEGIN OF UNLOCK_ZI_19_RENTALTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_19_RENTALTP,
      END OF ZI_19_RENTALTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_19_RENTALTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C10D5FD',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C1095FD',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C1195FD',
      END OF ZI_19_RENTALTP,
      BEGIN OF ZI_19_RENTALTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C1315FD',
      END OF ZI_19_RENTALTP_LOCK,
      BEGIN OF ZI_19_RENTALTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C12F5FD',
      END OF ZI_19_RENTALTP_MESSAGE,
      BEGIN OF ZI_19_RENTALTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEDA681131E0C1335FD',
      END OF ZI_19_RENTALTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_19_RENTALTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_19_RENTALTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EEDA681131E0C0FF5FD' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_19_RENTALTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_19_RENTALTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EEDA681134311669600',
      END OF ZI_19_RENTALTP,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_19_RENTALTP                 TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEDA681131E0C1035FD',
 ZI_19_RENTALTP_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEDA681131E0C10B5FD',
 ZI_19_RENTALTP_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEDA681131E0C1075FD',
 ZI_19_RENTALTP_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEDA681131E0C1175FD',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_19_RENTALTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  RENTALID                       TYPE STRING VALUE 'RENTALID',
  VIDEOUUID                      TYPE STRING VALUE 'VIDEOUUID',
  CUSTOMERUUID                   TYPE STRING VALUE 'CUSTOMERUUID',
  RENTAL_DATE                    TYPE STRING VALUE 'RENTAL_DATE',
  RETURNDATE                     TYPE STRING VALUE 'RETURNDATE',
  RENTALFEE                      TYPE STRING VALUE 'RENTALFEE',
  CURRENCYCODE                   TYPE STRING VALUE 'CURRENCYCODE',
  RENTALDATE                     TYPE STRING VALUE 'RENTALDATE',
      END OF ZI_19_RENTALTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_19_RENTALTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EEDA681131E0C1055FD',
      END OF ZI_19_RENTALTP,
    END OF SC_NODE_CATEGORY .
endinterface.
